services:
  postgres:
    image: postgres:15-alpine
    container_name: numino_postgres
    environment:
      POSTGRES_DB: numino_db
      POSTGRES_USER: numino_user
      POSTGRES_PASSWORD: numino_password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U numino_user -d numino_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:


